version: '3.8'
services:
  mysql-gahu:
    image: mysql:8.0
    container_name: mysql-gahu
    ports:
      - '8888:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'okokok'
    volumes:
      - ./configAdmin.sql:/docker-entrypoint-initdb.d/configAdmin.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql-gahu
    depends_on:
      - mysql-gahu

